Training and validation were performed with the SwissProt Training/Validation dataset used to train the DeepLoc 2.0 server. Testing was performed using the DeepLoc 2.0 Human Protein Atlas (HPA) test set. The data is available at: https://services.healthtech.dtu.dk/services/DeepLoc-2.0/4-Data.php

**References**

Thumuluri, V., Almagro Armenteros, J. J., Johansen, A. R., Nielsen, H. & Winther, O. (2022). *DeepLoc 2.0: multi-label subcellular localization prediction using protein language models.* Nucleic Acids Research, 50(W1), W228–W234. https://doi.org/10.1093/nar/gkac278

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

In [2]:
#exploring DeepLoc 2.0 Train/Validation set for multi-label subcellular localisation prediction 
df = pd.read_csv("Swissprot_Train_Validation_dataset.csv")
df.head()

,Unnamed: 0,ACC,Kingdom,Partition,Membrane,Cytoplasm,Nucleus,Extracellular,Cell membrane,Mitochondrion,Plastid,Endoplasmic reticulum,Lysosome/Vacuole,Golgi apparatus,Peroxisome,Sequence
0,0,Q28165,Metazoa,4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...
1,1,Q86U42,Metazoa,4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...
2,2,Q0GA42,Metazoa,3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAALGVRLRDCCSRGAVLLLFFSLSPRPPAAAAWLLGLR...
3,3,P82349,Metazoa,1,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAATEQQGSNGPVKKSMREKAVERRNVNKEHNSNFKAGY...
4,4,Q7L5N1,Metazoa,1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAATNGTGGSSGMEVDAAVVPSVMACGVTGSVSVALHPL...

In [3]:
df.shape #dimensions

(28303, 16)

In [4]:
df = df.dropna(subset = ["Sequence", "Nucleus"])
df.shape

(28303, 16)

In [5]:
df.index #no. of training examples

RangeIndex(start=0, stop=28303, step=1)

In [6]:
df.columns

Index(['Unnamed: 0', 'ACC', 'Kingdom', 'Partition', 'Membrane', 'Cytoplasm',
       'Nucleus', 'Extracellular', 'Cell membrane', 'Mitochondrion', 'Plastid',
       'Endoplasmic reticulum', 'Lysosome/Vacuole', 'Golgi apparatus',
       'Peroxisome', 'Sequence'],
      dtype='object')

In [7]:
df["Nucleus"].unique() #confirm use of 0/1 labels

array([1., 0.])

In [8]:
df["Nucleus"].value_counts()

Nucleus
0.0    18583
1.0     9720
Name: count, dtype: int64

In [9]:
df["Sequence"].str.len().describe() #stats for lengths of proteins

count    28303.000000
mean       556.901141
std        558.491431
min         40.000000
25%        261.000000
50%        433.000000
75%        681.000000
max      34350.000000
Name: Sequence, dtype: float64

In [10]:
df["Kingdom"].unique() #all eukaryotic according to https://doi.org/10.1093/nar/gkac278 (DeepLoc 2.0 paper)

array(['Metazoa', 'Viridiplantae', 'Fungi', 'Other'], dtype=object)

In [11]:
df["Kingdom"].value_counts()

Kingdom
Metazoa          16741
Fungi             5841
Viridiplantae     5116
Other              605
Name: count, dtype: int64

In [12]:
df["Partition"].unique()

array([4, 3, 1, 0, 2])

In [13]:
df["Partition"].value_counts()

Partition
0    5963
2    5731
3    5696
4    5462
1    5451
Name: count, dtype: int64

In [14]:
#produce the relevant training/validation dataframe
df = df[["Kingdom", "Partition", "Nucleus", "Sequence"]]
df.head()

,Kingdom,Partition,Nucleus,Sequence
0,Metazoa,4,1.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...
1,Metazoa,4,1.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...
2,Metazoa,3,0.0,MAAAAAAAAALGVRLRDCCSRGAVLLLFFSLSPRPPAAAAWLLGLR...
3,Metazoa,1,0.0,MAAAAAAAAATEQQGSNGPVKKSMREKAVERRNVNKEHNSNFKAGY...
4,Metazoa,1,1.0,MAAAAAAAAATNGTGGSSGMEVDAAVVPSVMACGVTGSVSVALHPL...

In [15]:
df.shape

(28303, 4)

In [16]:
#exploring DeepLoc 2.0 independent test set for multi-label subcellular localisation prediction 
df_test = pd.read_csv("hpa_testset.csv")
df_test.head()

,sid,Cell membrane,Cytoplasm,Endoplasmic reticulum,Golgi apparatus,Lysosome/Vacuole,Mitochondrion,Nucleus,Peroxisome,Lengths,fasta
0,ENSP00000355743,0,0,0,0,0,0,1,0,496,MAAAAGPGAALSPRPCDSDPATPGAQSPKDDNEDNSNDGTQPSKRR...
1,ENSP00000429628,0,0,0,0,0,0,1,0,173,MAAAALRDPAQVPVAADLLTDHEEGYVTFEDVAVYFSQEEWRLLDD...
2,ENSP00000266544,0,0,0,0,0,1,0,0,377,MAAAAQSRVVRVLSMSRSAITAIATSVCHGPPCRQLHHALMPHGKG...
3,ENSP00000470652,0,0,0,1,0,0,0,0,410,MAAAAVGAGHGAGGPGAASSSGGAREGARVAALCLLWYALSAGGNV...
4,ENSP00000460751,0,0,0,0,0,0,1,0,163,MAAAAVTRGTPGENSHHLKIFLPKKLLECLPRCPLLPPERLRWNTN...

In [17]:
df_test.shape

(1717, 11)

In [18]:
df_test.index

RangeIndex(start=0, stop=1717, step=1)

In [19]:
df_test.columns

Index(['sid', 'Cell membrane', 'Cytoplasm', 'Endoplasmic reticulum',
       'Golgi apparatus', 'Lysosome/Vacuole', 'Mitochondrion', 'Nucleus',
       'Peroxisome', 'Lengths', 'fasta'],
      dtype='object')

In [20]:
df_test.rename(columns={"fasta": "Sequence"}, inplace=True)
df_test = df_test.dropna(subset = ["Sequence", "Nucleus"])
df_test.shape

(1717, 11)

In [21]:
df_test.columns

Index(['sid', 'Cell membrane', 'Cytoplasm', 'Endoplasmic reticulum',
       'Golgi apparatus', 'Lysosome/Vacuole', 'Mitochondrion', 'Nucleus',
       'Peroxisome', 'Lengths', 'Sequence'],
      dtype='object')

In [22]:
df_test["Nucleus"].unique()

array([1, 0])

In [23]:
df_test["Nucleus"].value_counts()

Nucleus
1    893
0    824
Name: count, dtype: int64

In [24]:
df_test["Lengths"].describe() #shows test sequences are shorter on average & max length is also much shorter

count    1717.000000
mean      294.166570
std       373.415303
min        23.000000
25%        98.000000
50%       170.000000
75%       339.000000
max      4834.000000
Name: Lengths, dtype: float64

In [25]:
#produce relevant test set dataframe
df_test = df_test[["Nucleus", "Sequence"]]
df_test.head()

   Nucleus                                           Sequence
0        1  MAAAAGPGAALSPRPCDSDPATPGAQSPKDDNEDNSNDGTQPSKRR...
1        1  MAAAALRDPAQVPVAADLLTDHEEGYVTFEDVAVYFSQEEWRLLDD...
2        0  MAAAAQSRVVRVLSMSRSAITAIATSVCHGPPCRQLHHALMPHGKG...
3        0  MAAAAVGAGHGAGGPGAASSSGGAREGARVAALCLLWYALSAGGNV...
4        1  MAAAAVTRGTPGENSHHLKIFLPKKLLECLPRCPLLPPERLRWNTN...

In [26]:
#feature engineering - amino acid composition (as a fraction of sequence length)
#note: this method of feature engineering loses information about amino acid positions
aminoacids = {"A":0, "R":1, "N":2, "D":3, "C":4, "Q":5, "E":6, "G":7, "H":8, "I":9, "L":10, "K":11, "M":12, "F":13, "P":14, "S":15, "T":16, "W":17, "Y":18, "V":19}
def aminoacid_composition(sequence):
    features = np.zeros(20)
    length = len(sequence)
    for aa in sequence:
        for symbol in aminoacids:
            if aa == symbol:
                features[aminoacids[symbol]] += (1 / length)
    return features

df["input_vectors"] = df["Sequence"].apply(aminoacid_composition)

In [27]:
df.head()

,Kingdom,Partition,Nucleus,Sequence,input_vectors
0,Metazoa,4,1.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...,"[0.11437908496732031, 0.09150326797385624, 0.0..."
1,Metazoa,4,1.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...,"[0.11437908496732031, 0.09150326797385624, 0.0..."
2,Metazoa,3,0.0,MAAAAAAAAALGVRLRDCCSRGAVLLLFFSLSPRPPAAAAWLLGLR...,"[0.08937960042060973, 0.07781282860147205, 0.0..."
3,Metazoa,1,0.0,MAAAAAAAAATEQQGSNGPVKKSMREKAVERRNVNKEHNSNFKAGY...,"[0.05937500000000002, 0.05000000000000001, 0.0..."
4,Metazoa,1,1.0,MAAAAAAAAATNGTGGSSGMEVDAAVVPSVMACGVTGSVSVALHPL...,"[0.08562691131498473, 0.03669724770642202, 0.0..."

In [28]:
df_test["input_vectors"] = df_test["Sequence"].apply(aminoacid_composition)
df_test.head()

,Nucleus,Sequence,input_vectors
0,1,MAAAAGPGAALSPRPCDSDPATPGAQSPKDDNEDNSNDGTQPSKRR...,"[0.05443548387096771, 0.060483870967741896, 0...."
1,1,MAAAALRDPAQVPVAADLLTDHEEGYVTFEDVAVYFSQEEWRLLDD...,"[0.09826589595375719, 0.06358381502890172, 0.0..."
2,0,MAAAAQSRVVRVLSMSRSAITAIATSVCHGPPCRQLHHALMPHGKG...,"[0.07957559681697617, 0.07692307692307696, 0.0..."
3,0,MAAAAVGAGHGAGGPGAASSSGGAREGARVAALCLLWYALSAGGNV...,"[0.09512195121951224, 0.04390243902439025, 0.0..."
4,1,MAAAAVTRGTPGENSHHLKIFLPKKLLECLPRCPLLPPERLRWNTN...,"[0.06748466257668712, 0.07975460122699388, 0.0..."

In [29]:
#to use for separate "fromscratch_logistic_regression" exercise
df.to_csv("Protein_localisation_data/Training_CV_set.csv")
df_test.to_csv("Protein_localisation_data/Test_set.csv")

In [30]:
#logistic regression model with 5-fold cross-validation across homology-partitioned training datasets
#first fold of 5-fold cross-validation will use homology partition 0 as the validation set
train_df = df[df["Partition"].isin([1, 2, 3, 4])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 0]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

X_test = np.stack(df_test["input_vectors"].values)
y_test = np.stack(df_test["Nucleus"].values)

In [31]:
#feature scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)
X_test_scaled = scaler.transform(X_test)

In [32]:
#initialise the class
model = LogisticRegression()
#train the model
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [33]:
yhat = model.predict(X_cv_scaled)

#extract probability of output label 1
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
print(y_prob[0:200])

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

[0.63504313 0.26246396 0.22454369 0.09369078 0.16848342 0.21722055
 0.20912252 0.11049553 0.38125878 0.53314242 0.59546943 0.45895212
 0.14684296 0.13145989 0.18182744 0.38944828 0.4284688  0.14756092
 0.09878188 0.10706057 0.16730647 0.350556   0.54751671 0.51407833
 0.1731836  0.17552573 0.39587241 0.64404818 0.60058741 0.27471217
 0.11688224 0.14253809 0.04164947 0.23072247 0.23298356 0.23431967
 0.13986051 0.31703198 0.43331889 0.28708683 0.31390959 0.39083081
 0.30408598 0.09174857 0.42900763 0.16351228 0.12987442 0.38754149
 0.41999415 0.32288697 0.25562362 0.35403781 0.14873381 0.16273142
 0.69450251 0.68412564 0.0955861  0.14631229 0.17579966 0.23305231
 0.27742987 0.1423244  0.39059602 0.32251035 0.28614047 0.20953763
 0.21211737 0.43793618 0.44420996 0.18340265 0.72684999 0.49054425
 0.63497073 0.74961595 0.50899534 0.48162848 0.31088942 0.38808097
 0.69263213 0.69180339 0.70421833 0.47502569 0.45329709 0.85215049
 0.85336553 0.18966673 0.15716123 0.14982186 0.17626332 0.29313934
 0.22757122 0.30799068 0.43419503 0.43580984 0.43769586 0.52660457
 0.2661695  0.17502717 0.20645112 0.14204237 0.30227608 0.15028376
 0.2390663  0.18627221 0.58532786 0.36242064 0.33952899 0.3339348
 0.33473931 0.3061219  0.23165497 0.2693402  0.22332429 0.18990206
 0.1532127  0.07381006 0.21327849 0.583545   0.03604297 0.18246634
 0.07296315 0.37192026 0.27164126 0.21426529 0.2596605  0.6162903
 0.20112708 0.15866024 0.3051763  0.24310982 0.32293713 0.34499146
 0.22858838 0.23681774 0.23748434 0.37620245 0.46876405 0.30060315
 0.32731791 0.46750765 0.0843666  0.36937089 0.36354994 0.15522475
 0.02464266 0.45748328 0.16968549 0.3388629  0.53668552 0.37118238
 0.62316842 0.21048341 0.27348457 0.53659933 0.40071888 0.21033552
 0.25600403 0.23837499 0.26021633 0.24517652 0.2877404  0.57470262
 0.35857271 0.71263651 0.3511666  0.24871437 0.87572633 0.10997302
 0.38254458 0.3517546  0.21993754 0.10024312 0.30745552 0.20395901
 0.21500076 0.35309252 0.03737583 0.42390831 0.4471175  0.28026173
 0.25367059 0.80773869 0.30336009 0.2090202  0.14620298 0.31948924
 0.28410676 0.40317903 0.43925426 0.43673529 0.31568479 0.36791188
 0.46856621 0.20196486 0.30757231 0.32574538 0.21239142 0.20356457
 0.18266399 0.76286817]
Accuracy: 0.7273184638604729
              precision    recall  f1-score   support

         0.0       0.76      0.88      0.81      4092
         1.0       0.60      0.40      0.48      1871

    accuracy                           0.73      5963
   macro avg       0.68      0.64      0.65      5963
weighted avg       0.71      0.73      0.71      5963

[[3581  511]
 [1115  756]]

In [34]:
np.mean(y_cv)

np.float64(0.31376823746436355)

Accuracy is not a useful metric for the model's performance since the data is skewed (35% nuclear proteins in the cross-validation set, so approximately 27% being misclassified is only a marginally better outcome than if every protein was predicted to be non-nuclear).

For class 0, precision = 0.76, and for class 1, precision = 0.60, representing that the model correctly identifies a reasonably good fraction of cases that are actually 0/1. For class 0, recall = 0.88, whereas for class 1, recall = 0.40. The model is therefore significantly more accurate in identifying examples where y = 0 than y = 1, resulting in a high proportion of false negatives. This could be improved by lowering the threshold below 0.5, although this will involve a trade-off between precision and recall: precision will decrease, while recall increases.

In [35]:
#lower the threshold to 0.4
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.40
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.7174241153781653
              precision    recall  f1-score   support

         0.0       0.80      0.78      0.79      4092
         1.0       0.55      0.58      0.56      1871

    accuracy                           0.72      5963
   macro avg       0.67      0.68      0.68      5963
weighted avg       0.72      0.72      0.72      5963

[[3192  900]
 [ 785 1086]]

In [36]:
#lower the threshold to 0.3
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.3
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.6649337581754151
              precision    recall  f1-score   support

         0.0       0.85      0.62      0.72      4092
         1.0       0.48      0.76      0.59      1871

    accuracy                           0.66      5963
   macro avg       0.66      0.69      0.65      5963
weighted avg       0.73      0.66      0.68      5963

[[2542 1550]
 [ 448 1423]]

In [37]:
#2nd fold of 5-fold cross-validation will use homology partition 1 as the validation set
train_df = df[df["Partition"].isin([0, 2, 3, 4])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 1]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

In [38]:
X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)

#initialise the class
model = LogisticRegression()
#train the model
model.fit(X_train_scaled, y_train)

yhat = model.predict(X_cv_scaled)

#extract probability of output label 1
y_prob = model.predict_proba(X_cv_scaled)[:, 1]

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.6917996697853604
              precision    recall  f1-score   support

         0.0       0.72      0.85      0.78      3536
         1.0       0.59      0.40      0.48      1915

    accuracy                           0.69      5451
   macro avg       0.66      0.62      0.63      5451
weighted avg       0.68      0.69      0.67      5451

[[3010  526]
 [1154  761]]

In [39]:
#lower the threshold to 0.4
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.40
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.6936341955604476
              precision    recall  f1-score   support

         0.0       0.77      0.76      0.76      3536
         1.0       0.56      0.57      0.57      1915

    accuracy                           0.69      5451
   macro avg       0.66      0.67      0.66      5451
weighted avg       0.69      0.69      0.69      5451

[[2690  846]
 [ 824 1091]]

In [40]:
#lower the threshold to 0.3
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.3
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.6525408181984957
              precision    recall  f1-score   support

         0.0       0.81      0.60      0.69      3536
         1.0       0.50      0.74      0.60      1915

    accuracy                           0.65      5451
   macro avg       0.66      0.67      0.65      5451
weighted avg       0.70      0.65      0.66      5451

[[2136 1400]
 [ 494 1421]]

In [41]:
#3rd fold of 5-fold cross-validation will use homology partition 2 as the validation set
train_df = df[df["Partition"].isin([0, 1, 3, 4])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 2]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)

#initialise the class
model = LogisticRegression()
#train the model
model.fit(X_train_scaled, y_train)

yhat = model.predict(X_cv_scaled)

#extract probability of output label 1
y_prob = model.predict_proba(X_cv_scaled)[:, 1]

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.7253533414761821
              precision    recall  f1-score   support

         0.0       0.75      0.87      0.81      3800
         1.0       0.64      0.43      0.51      1931

    accuracy                           0.73      5731
   macro avg       0.69      0.65      0.66      5731
weighted avg       0.71      0.73      0.71      5731

[[3323  477]
 [1097  834]]

In [42]:
#lower the threshold to 0.4
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.40
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.722212528354563
              precision    recall  f1-score   support

         0.0       0.80      0.78      0.79      3800
         1.0       0.58      0.61      0.60      1931

    accuracy                           0.72      5731
   macro avg       0.69      0.69      0.69      5731
weighted avg       0.73      0.72      0.72      5731

[[2960  840]
 [ 752 1179]]

In [43]:
#lower the threshold to 0.3
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.3
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.6756238003838771
              precision    recall  f1-score   support

         0.0       0.85      0.62      0.72      3800
         1.0       0.51      0.79      0.62      1931

    accuracy                           0.68      5731
   macro avg       0.68      0.70      0.67      5731
weighted avg       0.74      0.68      0.68      5731

[[2353 1447]
 [ 412 1519]]

In [44]:
#4th fold of 5-fold cross-validation will use homology partition 3 as the validation set
train_df = df[df["Partition"].isin([0, 1, 2, 4])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 3]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)

#initialise the class
model = LogisticRegression()
#train the model
model.fit(X_train_scaled, y_train)

yhat = model.predict(X_cv_scaled)

#extract probability of output label 1
y_prob = model.predict_proba(X_cv_scaled)[:, 1]

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.7008426966292135
              precision    recall  f1-score   support

         0.0       0.73      0.87      0.79      3710
         1.0       0.61      0.39      0.47      1986

    accuracy                           0.70      5696
   macro avg       0.67      0.63      0.63      5696
weighted avg       0.69      0.70      0.68      5696

[[3226  484]
 [1220  766]]

In [45]:
#lower the threshold to 0.4
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.40
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.6966292134831461
              precision    recall  f1-score   support

         0.0       0.77      0.77      0.77      3710
         1.0       0.57      0.56      0.56      1986

    accuracy                           0.70      5696
   macro avg       0.67      0.66      0.67      5696
weighted avg       0.70      0.70      0.70      5696

[[2857  853]
 [ 875 1111]]

In [46]:
#lower the threshold to 0.3
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.3
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.6641502808988764
              precision    recall  f1-score   support

         0.0       0.83      0.61      0.70      3710
         1.0       0.51      0.76      0.61      1986

    accuracy                           0.66      5696
   macro avg       0.67      0.69      0.66      5696
weighted avg       0.72      0.66      0.67      5696

[[2264 1446]
 [ 467 1519]]

In [47]:
#5th fold of 5-fold cross-validation will use homology partition 4 as the validation set
train_df = df[df["Partition"].isin([0, 1, 2, 3])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 4]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)

#initialise the class
model = LogisticRegression()
#train the model
model.fit(X_train_scaled, y_train)

yhat = model.predict(X_cv_scaled)

#extract probability of output label 1
y_prob = model.predict_proba(X_cv_scaled)[:, 1]

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.6999267667521054
              precision    recall  f1-score   support

         0.0       0.71      0.88      0.79      3445
         1.0       0.66      0.39      0.49      2017

    accuracy                           0.70      5462
   macro avg       0.68      0.64      0.64      5462
weighted avg       0.69      0.70      0.68      5462

[[3027  418]
 [1221  796]]

In [48]:
#lower the threshold to 0.4
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.40
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.7010252654705236
              precision    recall  f1-score   support

         0.0       0.75      0.78      0.77      3445
         1.0       0.60      0.57      0.58      2017

    accuracy                           0.70      5462
   macro avg       0.68      0.67      0.68      5462
weighted avg       0.70      0.70      0.70      5462

[[2686  759]
 [ 874 1143]]

In [49]:
#lower the threshold to 0.3
y_prob = model.predict_proba(X_cv_scaled)[:, 1]
threshold = 0.3
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

Accuracy: 0.6724642987916514
              precision    recall  f1-score   support

         0.0       0.82      0.62      0.70      3445
         1.0       0.54      0.77      0.63      2017

    accuracy                           0.67      5462
   macro avg       0.68      0.69      0.67      5462
weighted avg       0.72      0.67      0.68      5462

[[2128 1317]
 [ 472 1545]]

Classification reports and confusion matrices are very similar across 5-fold cross-validation, suggesting that the initial plan to improve recall through a lower threshold would be effective across all folds. Lowering the threshold to 0.4 successfully improved the f1 score across folds from ~0.49 to ~0.57. An even lower threshold was avoided in the final model, as a threshold of 0.3 reduced precision to ~0.51.

In [50]:
#C value = inverse of regularisation strength in scikit-learn
C_values = [0.01, 0.1, 1, 10, 100]
accuracies = []
f1_scores = []

#cross-validation for different C-values using fold 5
for c in C_values:
    model = LogisticRegression(C=c)
    model.fit(X_train_scaled, y_train)
    y_prob = model.predict_proba(X_cv_scaled)[:, 1]
    threshold = 0.40
    yhat = (y_prob >= threshold).astype(int)
    accuracy = accuracy_score(y_cv, yhat)
    accuracies.append(accuracy)
    print(f"C={c}, Accuracy: {accuracy:.3f}")
    f1 = f1_score(y_cv, yhat)
    f1_scores.append(f1)
    print(f"C={c}, f1: {f1:.3f}")

C=0.01, Accuracy: 0.701
C=0.01, f1: 0.583
C=0.1, Accuracy: 0.701
C=0.1, f1: 0.583
C=1, Accuracy: 0.701
C=1, f1: 0.583
C=10, Accuracy: 0.701
C=10, f1: 0.583
C=100, Accuracy: 0.701
C=100, f1: 0.583

In [51]:
#final model
X_train = np.stack(df["input_vectors"].values)
y_train = np.stack(df["Nucleus"].values)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(C = 1.0)
model.fit(X_train_scaled, y_train)

y_prob = model.predict_proba(X_test_scaled)[:, 1]
threshold = 0.4
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_test, yhat))
print(classification_report(y_test, yhat))
print(confusion_matrix(y_test, yhat))

Accuracy: 0.5899825276645312
              precision    recall  f1-score   support

           0       0.56      0.66      0.61       824
           1       0.63      0.53      0.57       893

    accuracy                           0.59      1717
   macro avg       0.59      0.59      0.59      1717
weighted avg       0.60      0.59      0.59      1717

[[542 282]
 [422 471]]

In [52]:
y_prob = model.predict_proba(X_train_scaled)[:, 1]
threshold = 0.4
yhat = (y_prob >= threshold).astype(int)

print("Accuracy:", accuracy_score(y_train, yhat))
print(classification_report(y_train, yhat))
print(confusion_matrix(y_train, yhat))

Accuracy: 0.7095360915803979
              precision    recall  f1-score   support

         0.0       0.78      0.78      0.78     18583
         1.0       0.58      0.58      0.58      9720

    accuracy                           0.71     28303
   macro avg       0.68      0.68      0.68     28303
weighted avg       0.71      0.71      0.71     28303

[[14442  4141]
 [ 4080  5640]]