Training and validation were performed with the SwissProt Training/Validation dataset used to train the DeepLoc 2.0 server. Testing was performed using the DeepLoc 2.0 Human Protein Atlas (HPA) test set. The data is available at: https://services.healthtech.dtu.dk/services/DeepLoc-2.0/4-Data.php

**References**

Thumuluri, V., Almagro Armenteros, J. J., Johansen, A. R., Nielsen, H. & Winther, O. (2022). *DeepLoc 2.0: multi-label subcellular localization prediction using protein language models.* Nucleic Acids Research, 50(W1), W228–W234. https://doi.org/10.1093/nar/gkac278

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import BinaryCrossentropy

In [2]:
df = pd.read_csv("Swissprot_Train_Validation_dataset.csv")
df.head()

,Unnamed: 0,ACC,Kingdom,Partition,Membrane,Cytoplasm,Nucleus,Extracellular,Cell membrane,Mitochondrion,Plastid,Endoplasmic reticulum,Lysosome/Vacuole,Golgi apparatus,Peroxisome,Sequence
0,0,Q28165,Metazoa,4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...
1,1,Q86U42,Metazoa,4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...
2,2,Q0GA42,Metazoa,3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAALGVRLRDCCSRGAVLLLFFSLSPRPPAAAAWLLGLR...
3,3,P82349,Metazoa,1,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAATEQQGSNGPVKKSMREKAVERRNVNKEHNSNFKAGY...
4,4,Q7L5N1,Metazoa,1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,MAAAAAAAAATNGTGGSSGMEVDAAVVPSVMACGVTGSVSVALHPL...

In [3]:
df.shape

(28303, 16)

In [4]:
df = df.dropna(subset = ["Partition", "Sequence", "Nucleus"])
df.shape

(28303, 16)

In [5]:
df = df[["Partition", "Nucleus", "Sequence"]]
df.head()

   Partition  Nucleus                                           Sequence
0          4      1.0  MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...
1          4      1.0  MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...
2          3      0.0  MAAAAAAAAALGVRLRDCCSRGAVLLLFFSLSPRPPAAAAWLLGLR...
3          1      0.0  MAAAAAAAAATEQQGSNGPVKKSMREKAVERRNVNKEHNSNFKAGY...
4          1      1.0  MAAAAAAAAATNGTGGSSGMEVDAAVVPSVMACGVTGSVSVALHPL...

In [6]:
df_test = pd.read_csv("hpa_testset.csv")
df_test.head()

,sid,Cell membrane,Cytoplasm,Endoplasmic reticulum,Golgi apparatus,Lysosome/Vacuole,Mitochondrion,Nucleus,Peroxisome,Lengths,fasta
0,ENSP00000355743,0,0,0,0,0,0,1,0,496,MAAAAGPGAALSPRPCDSDPATPGAQSPKDDNEDNSNDGTQPSKRR...
1,ENSP00000429628,0,0,0,0,0,0,1,0,173,MAAAALRDPAQVPVAADLLTDHEEGYVTFEDVAVYFSQEEWRLLDD...
2,ENSP00000266544,0,0,0,0,0,1,0,0,377,MAAAAQSRVVRVLSMSRSAITAIATSVCHGPPCRQLHHALMPHGKG...
3,ENSP00000470652,0,0,0,1,0,0,0,0,410,MAAAAVGAGHGAGGPGAASSSGGAREGARVAALCLLWYALSAGGNV...
4,ENSP00000460751,0,0,0,0,0,0,1,0,163,MAAAAVTRGTPGENSHHLKIFLPKKLLECLPRCPLLPPERLRWNTN...

In [7]:
df_test.shape

(1717, 11)

In [8]:
df_test.rename(columns={"fasta": "Sequence"}, inplace=True)
df_test = df_test.dropna(subset = ["Sequence", "Nucleus"])

In [9]:
df_test = df_test[["Nucleus", "Sequence"]]
df_test.head()

   Nucleus                                           Sequence
0        1  MAAAAGPGAALSPRPCDSDPATPGAQSPKDDNEDNSNDGTQPSKRR...
1        1  MAAAALRDPAQVPVAADLLTDHEEGYVTFEDVAVYFSQEEWRLLDD...
2        0  MAAAAQSRVVRVLSMSRSAITAIATSVCHGPPCRQLHHALMPHGKG...
3        0  MAAAAVGAGHGAGGPGAASSSGGAREGARVAALCLLWYALSAGGNV...
4        1  MAAAAVTRGTPGENSHHLKIFLPKKLLECLPRCPLLPPERLRWNTN...

In [10]:
#feature engineering - dipeptide composition (as a fraction of number of dipeptides, which is = (sequence length) - 1 )
#dipeptide composition includes some positional information: which amino acids often occur adjacent to each other

amino_acids = "ACDEFGHIKLMNPQRSTVWY"

aa_to_idx = {aa: i for i, aa in enumerate(amino_acids)}

def dipeptide_comp(sequence):
    # Convert valid amino acids to indices
    indices = np.array([aa_to_idx.get(aa, -1) for aa in sequence])

    first = indices[:-1]
    second = indices[1:]

    # Keep only pairs residues are standard amino acids (not X, B, U)
    valid = (first >= 0) & (second >= 0)

    first = first[valid]
    second = second[valid]

    # Encode each dipeptide as an integer 0–399
    dipeptide_indices = first * 20 + second

    counts = np.bincount(dipeptide_indices, minlength=400)

    # Normalise by number of valid dipeptides
    n_valid = len(dipeptide_indices)

    if n_valid == 0:
        return np.zeros(400)

    return counts / n_valid

In [11]:
df["input_vectors"] = df["Sequence"].apply(dipeptide_comp)
df.head()

,Partition,Nucleus,Sequence,input_vectors
0,4,1.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...,"[0.03278688524590164, 0.0, 0.00327868852459016..."
1,4,1.0,MAAAAAAAAAAGAAGGRGSGPGRRRHLVPGAGGEAGEGAPGGAGDY...,"[0.03278688524590164, 0.0, 0.00327868852459016..."
2,3,0.0,MAAAAAAAAALGVRLRDCCSRGAVLLLFFSLSPRPPAAAAWLLGLR...,"[0.022105263157894735, 0.002105263157894737, 0..."
3,1,0.0,MAAAAAAAAATEQQGSNGPVKKSMREKAVERRNVNKEHNSNFKAGY...,"[0.025078369905956112, 0.0, 0.0031347962382445..."
4,1,1.0,MAAAAAAAAATNGTGGSSGMEVDAAVVPSVMACGVTGSVSVALHPL...,"[0.027607361963190184, 0.003067484662576687, 0..."

In [12]:
df_test["input_vectors"] = df_test["Sequence"].apply(dipeptide_comp)
df_test.head()

,Nucleus,Sequence,input_vectors
0,1,MAAAAGPGAALSPRPCDSDPATPGAQSPKDDNEDNSNDGTQPSKRR...,"[0.014141414141414142, 0.0, 0.0, 0.00808080808..."
1,1,MAAAALRDPAQVPVAADLLTDHEEGYVTFEDVAVYFSQEEWRLLDD...,"[0.023255813953488372, 0.0, 0.0058139534883720..."
2,0,MAAAAQSRVVRVLSMSRSAITAIATSVCHGPPCRQLHHALMPHGKG...,"[0.007978723404255319, 0.0, 0.0, 0.00265957446..."
3,0,MAAAAVGAGHGAGGPGAASSSGGAREGARVAALCLLWYALSAGGNV...,"[0.014669926650366748, 0.0, 0.0024449877750611..."
4,1,MAAAAVTRGTPGENSHHLKIFLPKKLLECLPRCPLLPPERLRWNTN...,"[0.024691358024691357, 0.006172839506172839, 0..."

In [13]:
#5-fold cross-validation across homology-partitioned training datasets
#first fold of 5-fold cross-validation will use homology partition 0 as the validation set
train_df = df[df["Partition"].isin([1, 2, 3, 4])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 0]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

X_test = np.stack(df_test["input_vectors"].values)
y_test = np.stack(df_test["Nucleus"].values)

In [14]:
#feature scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)

In [15]:
model = Sequential([
    Dense(units = 128, activation = 'relu', kernel_regularizer = tf.keras.regularizers.l2(0.01)),
    Dense(units = 64, activation = 'relu', kernel_regularizer = tf.keras.regularizers.l2(0.01)),
    Dense(units = 1, activation = 'sigmoid', kernel_regularizer = tf.keras.regularizers.l2(0.01))
])

model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01), loss = BinaryCrossentropy(), metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ])

model.fit(X_train_scaled, y_train, epochs = 50)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.7106 - loss: 0.7348 - precision: 0.6246 - recall: 0.4417
Epoch 2/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7217 - loss: 0.6012 - precision: 0.6419 - recall: 0.4701
Epoch 3/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7205 - loss: 0.5910 - precision: 0.6409 - recall: 0.4648
Epoch 4/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7223 - loss: 0.5879 - precision: 0.6450 - recall: 0.4664
Epoch 5/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7222 - loss: 0.5874 - precision: 0.6413 - recall: 0.4750
Epoch 6/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7192 - loss: 0.5877 - precision: 0.6343 - recall: 0.4746
Epoch 7/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7189 - loss: 0.5861 - precision: 0.6330 - recall: 0.4760
Epoch 8/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7232 - loss: 0.5864 - precision: 0.6408 - recall: 0.4827
Epoch 9/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7253 - loss: 0.5856 - precision: 0.6432 - recall: 0.4899
Epoch 10/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7211 - loss: 0.5860 - precision: 0.6355 - recall: 0.4834
Epoch 11/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7237 - loss: 0.5864 - precision: 0.6415 - recall: 0.4841
Epoch 12/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7246 - loss: 0.5850 - precision: 0.6422 - recall: 0.4881
Epoch 13/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7241 - loss: 0.5860 - precision: 0.6441 - recall: 0.4797
Epoch 14/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7212 - loss: 0.5859 - precision: 0.6387 - recall: 0.4753
Epoch 15/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7239 - loss: 0.5855 - precision: 0.6421 - recall: 0.4843
Epoch 16/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7222 - loss: 0.5866 - precision: 0.6354 - recall: 0.4915
Epoch 17/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7250 - loss: 0.5843 - precision: 0.6437 - recall: 0.4867
Epoch 18/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7243 - loss: 0.5847 - precision: 0.6393 - recall: 0.4941
Epoch 19/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7226 - loss: 0.5851 - precision: 0.6403 - recall: 0.4802
Epoch 20/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7235 - loss: 0.5853 - precision: 0.6412 - recall: 0.4834
Epoch 21/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7220 - loss: 0.5851 - precision: 0.6367 - recall: 0.4862
Epoch 22/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7242 - loss: 0.5854 - precision: 0.6433 - recall: 0.4827
Epoch 23/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7217 - loss: 0.5860 - precision: 0.6404 - recall: 0.4739
Epoch 24/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7197 - loss: 0.5856 - precision: 0.6366 - recall: 0.4715
Epoch 25/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7227 - loss: 0.5854 - precision: 0.6402 - recall: 0.4812
Epoch 26/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7214 - loss: 0.5854 - precision: 0.6392 - recall: 0.4757
Epoch 27/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7180 - loss: 0.5871 - precision: 0.6287 - recall: 0.4820
Epoch 28/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7210 - loss: 0.5851 - precision: 0.6370 - recall: 0.4789
Epoch 29/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7221 - loss: 0.5844 - precision: 0.6385 - recall: 0.4820
Epoch 30/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7209 - loss: 0.5851 - precision: 0.6359 - recall: 0.4807
Epoch 31/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7219 - loss: 0.5847 - precision: 0.6367 - recall: 0.4854
Epoch 32/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7224 - loss: 0.5844 - precision: 0.6358 - recall: 0.4911
Epoch 33/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7228 - loss: 0.5860 - precision: 0.6403 - recall: 0.4815
Epoch 34/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7222 - loss: 0.5843 - precision: 0.6387 - recall: 0.4820
Epoch 35/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7213 - loss: 0.5842 - precision: 0.6365 - recall: 0.4820
Epoch 36/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7228 - loss: 0.5850 - precision: 0.6412 - recall: 0.4793
Epoch 37/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7251 - loss: 0.5850 - precision: 0.6457 - recall: 0.4822
Epoch 38/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7230 - loss: 0.5860 - precision: 0.6422 - recall: 0.4778
Epoch 39/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7249 - loss: 0.5849 - precision: 0.6414 - recall: 0.4922
Epoch 40/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7197 - loss: 0.5858 - precision: 0.6350 - recall: 0.4753
Epoch 41/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7234 - loss: 0.5858 - precision: 0.6433 - recall: 0.4775
Epoch 42/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7246 - loss: 0.5854 - precision: 0.6420 - recall: 0.4883
Epoch 43/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7223 - loss: 0.5856 - precision: 0.6382 - recall: 0.4840
Epoch 44/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7226 - loss: 0.5850 - precision: 0.6408 - recall: 0.4789
Epoch 45/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7235 - loss: 0.5869 - precision: 0.6410 - recall: 0.4839
Epoch 46/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7228 - loss: 0.5857 - precision: 0.6410 - recall: 0.4797
Epoch 47/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7222 - loss: 0.5854 - precision: 0.6397 - recall: 0.4793
Epoch 48/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7175 - loss: 0.5857 - precision: 0.6289 - recall: 0.4784
Epoch 49/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7216 - loss: 0.5845 - precision: 0.6376 - recall: 0.4812
Epoch 50/50
699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7218 - loss: 0.5848 - precision: 0.6382 - recall: 0.4810

In [16]:
results = model.evaluate(X_train_scaled, y_train, return_dict=True)

print(results)

699/699 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7303 - loss: 0.5753 - precision: 0.6500 - recall: 0.5039
{'accuracy': 0.7303491234779358, 'loss': 0.5752819776535034, 'precision': 0.6499589085578918, 'recall': 0.5038858652114868}

In [17]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.5
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

187/187 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy (cv set): 0.73469730001677
              precision    recall  f1-score   support

         0.0       0.78      0.86      0.82      4092
         1.0       0.60      0.46      0.52      1871

    accuracy                           0.73      5963
   macro avg       0.69      0.66      0.67      5963
weighted avg       0.72      0.73      0.72      5963

[[3515  577]
 [1005  866]]

In [18]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.45
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

187/187 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy (cv set): 0.7224551400301862
              precision    recall  f1-score   support

         0.0       0.79      0.80      0.80      4092
         1.0       0.56      0.54      0.55      1871

    accuracy                           0.72      5963
   macro avg       0.68      0.67      0.68      5963
weighted avg       0.72      0.72      0.72      5963

[[3293  799]
 [ 856 1015]]

In [19]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.40 #gives quite low precision, so lower thresholds will not be tried
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

187/187 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy (cv set): 0.6937782995136677
              precision    recall  f1-score   support

         0.0       0.84      0.69      0.76      4092
         1.0       0.51      0.71      0.59      1871

    accuracy                           0.69      5963
   macro avg       0.67      0.70      0.67      5963
weighted avg       0.73      0.69      0.70      5963

[[2816 1276]
 [ 550 1321]]

In [20]:
#2nd fold of 5-fold cross-validation will use homology partition 1 as the validation set
train_df = df[df["Partition"].isin([0, 2, 3, 4])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 1]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)

model.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7302 - loss: 0.5777 - precision: 0.6448 - recall: 0.4675
Epoch 2/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7305 - loss: 0.5782 - precision: 0.6463 - recall: 0.4659
Epoch 3/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7294 - loss: 0.5775 - precision: 0.6433 - recall: 0.4661
Epoch 4/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7321 - loss: 0.5780 - precision: 0.6468 - recall: 0.4748
Epoch 5/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7313 - loss: 0.5772 - precision: 0.6478 - recall: 0.4674
Epoch 6/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7290 - loss: 0.5780 - precision: 0.6404 - recall: 0.4707
Epoch 7/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7283 - loss: 0.5773 - precision: 0.6408 - recall: 0.4650
Epoch 8/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7304 - loss: 0.5771 - precision: 0.6434 - recall: 0.4726
Epoch 9/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7337 - loss: 0.5773 - precision: 0.6482 - recall: 0.4820
Epoch 10/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7283 - loss: 0.5776 - precision: 0.6414 - recall: 0.4637
Epoch 11/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7280 - loss: 0.5778 - precision: 0.6368 - recall: 0.4742
Epoch 12/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7285 - loss: 0.5763 - precision: 0.6365 - recall: 0.4782
Epoch 13/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7280 - loss: 0.5777 - precision: 0.6343 - recall: 0.4807
Epoch 14/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7311 - loss: 0.5761 - precision: 0.6420 - recall: 0.4810
Epoch 15/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7306 - loss: 0.5764 - precision: 0.6453 - recall: 0.4691
Epoch 16/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7256 - loss: 0.5766 - precision: 0.6295 - recall: 0.4778
Epoch 17/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7301 - loss: 0.5774 - precision: 0.6409 - recall: 0.4771
Epoch 18/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7271 - loss: 0.5766 - precision: 0.6315 - recall: 0.4826
Epoch 19/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7302 - loss: 0.5763 - precision: 0.6416 - recall: 0.4760
Epoch 20/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7298 - loss: 0.5769 - precision: 0.6424 - recall: 0.4712
Epoch 21/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7285 - loss: 0.5766 - precision: 0.6349 - recall: 0.4825
Epoch 22/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7302 - loss: 0.5760 - precision: 0.6387 - recall: 0.4837
Epoch 23/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7317 - loss: 0.5775 - precision: 0.6457 - recall: 0.4753
Epoch 24/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7285 - loss: 0.5771 - precision: 0.6351 - recall: 0.4823
Epoch 25/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7262 - loss: 0.5781 - precision: 0.6351 - recall: 0.4659
Epoch 26/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7290 - loss: 0.5769 - precision: 0.6367 - recall: 0.4812
Epoch 27/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7294 - loss: 0.5761 - precision: 0.6431 - recall: 0.4669
Epoch 28/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7284 - loss: 0.5776 - precision: 0.6360 - recall: 0.4787
Epoch 29/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7301 - loss: 0.5760 - precision: 0.6410 - recall: 0.4767
Epoch 30/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7292 - loss: 0.5782 - precision: 0.6397 - recall: 0.4741
Epoch 31/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7280 - loss: 0.5780 - precision: 0.6404 - recall: 0.4647
Epoch 32/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7298 - loss: 0.5768 - precision: 0.6403 - recall: 0.4767
Epoch 33/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7308 - loss: 0.5762 - precision: 0.6428 - recall: 0.4770
Epoch 34/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7290 - loss: 0.5777 - precision: 0.6399 - recall: 0.4721
Epoch 35/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7304 - loss: 0.5766 - precision: 0.6421 - recall: 0.4760
Epoch 36/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7282 - loss: 0.5766 - precision: 0.6367 - recall: 0.4752
Epoch 37/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7300 - loss: 0.5770 - precision: 0.6412 - recall: 0.4753
Epoch 38/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7285 - loss: 0.5774 - precision: 0.6386 - recall: 0.4723
Epoch 39/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7292 - loss: 0.5775 - precision: 0.6391 - recall: 0.4756
Epoch 40/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7293 - loss: 0.5765 - precision: 0.6395 - recall: 0.4757
Epoch 41/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7307 - loss: 0.5763 - precision: 0.6427 - recall: 0.4764
Epoch 42/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7290 - loss: 0.5787 - precision: 0.6399 - recall: 0.4725
Epoch 43/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7305 - loss: 0.5770 - precision: 0.6403 - recall: 0.4812
Epoch 44/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7300 - loss: 0.5775 - precision: 0.6419 - recall: 0.4741
Epoch 45/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7275 - loss: 0.5774 - precision: 0.6375 - recall: 0.4683
Epoch 46/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7288 - loss: 0.5782 - precision: 0.6394 - recall: 0.4724
Epoch 47/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7324 - loss: 0.5767 - precision: 0.6469 - recall: 0.4765
Epoch 48/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7309 - loss: 0.5770 - precision: 0.6431 - recall: 0.4767
Epoch 49/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7264 - loss: 0.5793 - precision: 0.6378 - recall: 0.4601
Epoch 50/50
715/715 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7296 - loss: 0.5790 - precision: 0.6410 - recall: 0.4733

In [21]:
results = model.evaluate(X_train_scaled, y_train, return_dict=True)

print(results)

715/715 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7349 - loss: 0.5678 - precision: 0.6514 - recall: 0.4814
{'accuracy': 0.7348591089248657, 'loss': 0.5678497552871704, 'precision': 0.6513522863388062, 'recall': 0.4813581109046936}

In [22]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.5
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

171/171 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy (cv set): 0.7002384883507613
              precision    recall  f1-score   support

         0.0       0.74      0.83      0.78      3536
         1.0       0.60      0.45      0.52      1915

    accuracy                           0.70      5451
   macro avg       0.67      0.64      0.65      5451
weighted avg       0.69      0.70      0.69      5451

[[2947  589]
 [1045  870]]

In [23]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.45
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

171/171 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Accuracy (cv set): 0.6984039625756742
              precision    recall  f1-score   support

         0.0       0.76      0.78      0.77      3536
         1.0       0.57      0.56      0.56      1915

    accuracy                           0.70      5451
   macro avg       0.67      0.67      0.67      5451
weighted avg       0.70      0.70      0.70      5451

[[2742  794]
 [ 850 1065]]

In [24]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.40
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

171/171 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy (cv set): 0.6967528893780958
              precision    recall  f1-score   support

         0.0       0.79      0.72      0.76      3536
         1.0       0.56      0.65      0.60      1915

    accuracy                           0.70      5451
   macro avg       0.68      0.69      0.68      5451
weighted avg       0.71      0.70      0.70      5451

[[2554  982]
 [ 671 1244]]

In [25]:
#3rd fold of 5-fold cross-validation will use homology partition 2 as the validation set
train_df = df[df["Partition"].isin([0, 1, 3, 4])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 2]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)


model.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7235 - loss: 0.5848 - precision: 0.6373 - recall: 0.4613
Epoch 2/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7211 - loss: 0.5853 - precision: 0.6297 - recall: 0.4655
Epoch 3/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7218 - loss: 0.5855 - precision: 0.6328 - recall: 0.4617
Epoch 4/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7228 - loss: 0.5859 - precision: 0.6345 - recall: 0.4636
Epoch 5/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7229 - loss: 0.5873 - precision: 0.6311 - recall: 0.4743
Epoch 6/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7219 - loss: 0.5856 - precision: 0.6328 - recall: 0.4622
Epoch 7/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7224 - loss: 0.5852 - precision: 0.6301 - recall: 0.4737
Epoch 8/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7219 - loss: 0.5879 - precision: 0.6339 - recall: 0.4592
Epoch 9/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7251 - loss: 0.5853 - precision: 0.6389 - recall: 0.4676
Epoch 10/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7224 - loss: 0.5848 - precision: 0.6316 - recall: 0.4691
Epoch 11/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7235 - loss: 0.5845 - precision: 0.6301 - recall: 0.4812
Epoch 12/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7195 - loss: 0.5868 - precision: 0.6265 - recall: 0.4631
Epoch 13/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7211 - loss: 0.5854 - precision: 0.6279 - recall: 0.4705
Epoch 14/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7236 - loss: 0.5854 - precision: 0.6326 - recall: 0.4743
Epoch 15/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7208 - loss: 0.5853 - precision: 0.6280 - recall: 0.4687
Epoch 16/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7205 - loss: 0.5850 - precision: 0.6309 - recall: 0.4580
Epoch 17/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7207 - loss: 0.5868 - precision: 0.6271 - recall: 0.4704
Epoch 18/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7225 - loss: 0.5858 - precision: 0.6324 - recall: 0.4680
Epoch 19/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7212 - loss: 0.5862 - precision: 0.6314 - recall: 0.4612
Epoch 20/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7218 - loss: 0.5860 - precision: 0.6295 - recall: 0.4710
Epoch 21/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7206 - loss: 0.5867 - precision: 0.6277 - recall: 0.4680
Epoch 22/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7211 - loss: 0.5862 - precision: 0.6267 - recall: 0.4740
Epoch 23/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7212 - loss: 0.5876 - precision: 0.6283 - recall: 0.4700
Epoch 24/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7212 - loss: 0.5863 - precision: 0.6269 - recall: 0.4740
Epoch 25/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7220 - loss: 0.5867 - precision: 0.6321 - recall: 0.4651
Epoch 26/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7229 - loss: 0.5851 - precision: 0.6314 - recall: 0.4732
Epoch 27/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7218 - loss: 0.5860 - precision: 0.6312 - recall: 0.4663
Epoch 28/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7234 - loss: 0.5875 - precision: 0.6356 - recall: 0.4651
Epoch 29/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7255 - loss: 0.5849 - precision: 0.6391 - recall: 0.4696
Epoch 30/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7214 - loss: 0.5875 - precision: 0.6306 - recall: 0.4649
Epoch 31/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7204 - loss: 0.5854 - precision: 0.6280 - recall: 0.4651
Epoch 32/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7224 - loss: 0.5847 - precision: 0.6312 - recall: 0.4704
Epoch 33/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7227 - loss: 0.5846 - precision: 0.6317 - recall: 0.4707
Epoch 34/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7240 - loss: 0.5855 - precision: 0.6351 - recall: 0.4702
Epoch 35/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7220 - loss: 0.5852 - precision: 0.6316 - recall: 0.4666
Epoch 36/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7225 - loss: 0.5846 - precision: 0.6312 - recall: 0.4712
Epoch 37/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7205 - loss: 0.5871 - precision: 0.6289 - recall: 0.4632
Epoch 38/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7232 - loss: 0.5857 - precision: 0.6316 - recall: 0.4745
Epoch 39/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7218 - loss: 0.5876 - precision: 0.6292 - recall: 0.4717
Epoch 40/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7225 - loss: 0.5852 - precision: 0.6311 - recall: 0.4716
Epoch 41/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7199 - loss: 0.5860 - precision: 0.6256 - recall: 0.4689
Epoch 42/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7257 - loss: 0.5849 - precision: 0.6388 - recall: 0.4718
Epoch 43/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7228 - loss: 0.5855 - precision: 0.6315 - recall: 0.4727
Epoch 44/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7240 - loss: 0.5846 - precision: 0.6348 - recall: 0.4717
Epoch 45/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7232 - loss: 0.5865 - precision: 0.6333 - recall: 0.4696
Epoch 46/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7223 - loss: 0.5862 - precision: 0.6305 - recall: 0.4713
Epoch 47/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7236 - loss: 0.5855 - precision: 0.6357 - recall: 0.4660
Epoch 48/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7218 - loss: 0.5859 - precision: 0.6302 - recall: 0.4687
Epoch 49/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7220 - loss: 0.5857 - precision: 0.6303 - recall: 0.4699
Epoch 50/50
706/706 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7244 - loss: 0.5848 - precision: 0.6339 - recall: 0.4764

In [26]:
results = model.evaluate(X_train_scaled, y_train, return_dict=True)

print(results)

706/706 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7331 - loss: 0.5771 - precision: 0.6562 - recall: 0.4759
{'accuracy': 0.7331206798553467, 'loss': 0.5771031975746155, 'precision': 0.6562223434448242, 'recall': 0.47592759132385254}

In [27]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.5
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy (cv set): 0.7368696562554528
              precision    recall  f1-score   support

         0.0       0.77      0.86      0.81      3800
         1.0       0.64      0.49      0.56      1931

    accuracy                           0.74      5731
   macro avg       0.71      0.68      0.68      5731
weighted avg       0.73      0.74      0.73      5731

[[3282  518]
 [ 990  941]]

In [28]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.45
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy (cv set): 0.7333798638980981
              precision    recall  f1-score   support

         0.0       0.79      0.81      0.80      3800
         1.0       0.61      0.59      0.60      1931

    accuracy                           0.73      5731
   macro avg       0.70      0.70      0.70      5731
weighted avg       0.73      0.73      0.73      5731

[[3065  735]
 [ 793 1138]]

In [29]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.40
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy (cv set): 0.7185482463793404
              precision    recall  f1-score   support

         0.0       0.81      0.75      0.78      3800
         1.0       0.57      0.66      0.61      1931

    accuracy                           0.72      5731
   macro avg       0.69      0.71      0.70      5731
weighted avg       0.73      0.72      0.72      5731

[[2835  965]
 [ 648 1283]]

In [30]:
#4th fold of 5-fold cross-validation will use homology partition 3 as the validation set
train_df = df[df["Partition"].isin([0, 1, 2, 4])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 3]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)

model.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7267 - loss: 0.5814 - precision: 0.6368 - recall: 0.4682
Epoch 2/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7268 - loss: 0.5804 - precision: 0.6389 - recall: 0.4630
Epoch 3/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7281 - loss: 0.5797 - precision: 0.6418 - recall: 0.4643
Epoch 4/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7290 - loss: 0.5795 - precision: 0.6418 - recall: 0.4705
Epoch 5/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7292 - loss: 0.5805 - precision: 0.6425 - recall: 0.4696
Epoch 6/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7280 - loss: 0.5803 - precision: 0.6422 - recall: 0.4624
Epoch 7/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7273 - loss: 0.5810 - precision: 0.6413 - recall: 0.4600
Epoch 8/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7278 - loss: 0.5796 - precision: 0.6415 - recall: 0.4634
Epoch 9/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7271 - loss: 0.5789 - precision: 0.6375 - recall: 0.4687
Epoch 10/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7299 - loss: 0.5796 - precision: 0.6453 - recall: 0.4670
Epoch 11/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7220 - loss: 0.5814 - precision: 0.6276 - recall: 0.4611
Epoch 12/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7265 - loss: 0.5806 - precision: 0.6382 - recall: 0.4628
Epoch 13/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7238 - loss: 0.5803 - precision: 0.6296 - recall: 0.4679
Epoch 14/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7268 - loss: 0.5803 - precision: 0.6405 - recall: 0.4593
Epoch 15/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7263 - loss: 0.5803 - precision: 0.6398 - recall: 0.4576
Epoch 16/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7268 - loss: 0.5799 - precision: 0.6402 - recall: 0.4597
Epoch 17/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7265 - loss: 0.5790 - precision: 0.6371 - recall: 0.4656
Epoch 18/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7269 - loss: 0.5801 - precision: 0.6399 - recall: 0.4616
Epoch 19/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7285 - loss: 0.5793 - precision: 0.6424 - recall: 0.4653
Epoch 20/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7277 - loss: 0.5808 - precision: 0.6388 - recall: 0.4699
Epoch 21/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7288 - loss: 0.5792 - precision: 0.6412 - recall: 0.4706
Epoch 22/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7249 - loss: 0.5806 - precision: 0.6333 - recall: 0.4652
Epoch 23/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7275 - loss: 0.5801 - precision: 0.6407 - recall: 0.4630
Epoch 24/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7263 - loss: 0.5800 - precision: 0.6381 - recall: 0.4619
Epoch 25/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7282 - loss: 0.5796 - precision: 0.6382 - recall: 0.4744
Epoch 26/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7271 - loss: 0.5800 - precision: 0.6409 - recall: 0.4600
Epoch 27/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7279 - loss: 0.5796 - precision: 0.6427 - recall: 0.4606
Epoch 28/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7269 - loss: 0.5804 - precision: 0.6412 - recall: 0.4581
Epoch 29/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7280 - loss: 0.5809 - precision: 0.6412 - recall: 0.4651
Epoch 30/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7257 - loss: 0.5795 - precision: 0.6384 - recall: 0.4569
Epoch 31/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7270 - loss: 0.5815 - precision: 0.6382 - recall: 0.4666
Epoch 32/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7244 - loss: 0.5802 - precision: 0.6323 - recall: 0.4648
Epoch 33/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7267 - loss: 0.5800 - precision: 0.6380 - recall: 0.4651
Epoch 34/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7247 - loss: 0.5807 - precision: 0.6361 - recall: 0.4563
Epoch 35/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7287 - loss: 0.5789 - precision: 0.6436 - recall: 0.4635
Epoch 36/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7247 - loss: 0.5799 - precision: 0.6358 - recall: 0.4573
Epoch 37/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7258 - loss: 0.5807 - precision: 0.6379 - recall: 0.4594
Epoch 38/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7273 - loss: 0.5792 - precision: 0.6364 - recall: 0.4732
Epoch 39/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7249 - loss: 0.5811 - precision: 0.6327 - recall: 0.4670
Epoch 40/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7291 - loss: 0.5798 - precision: 0.6432 - recall: 0.4675
Epoch 41/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7286 - loss: 0.5797 - precision: 0.6395 - recall: 0.4735
Epoch 42/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7295 - loss: 0.5793 - precision: 0.6412 - recall: 0.4750
Epoch 43/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7264 - loss: 0.5810 - precision: 0.6386 - recall: 0.4615
Epoch 44/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7242 - loss: 0.5805 - precision: 0.6347 - recall: 0.4567
Epoch 45/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7251 - loss: 0.5803 - precision: 0.6355 - recall: 0.4610
Epoch 46/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7300 - loss: 0.5800 - precision: 0.6465 - recall: 0.4647
Epoch 47/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7284 - loss: 0.5808 - precision: 0.6422 - recall: 0.4653
Epoch 48/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7250 - loss: 0.5793 - precision: 0.6347 - recall: 0.4624
Epoch 49/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7273 - loss: 0.5799 - precision: 0.6378 - recall: 0.4691
Epoch 50/50
707/707 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7248 - loss: 0.5814 - precision: 0.6377 - recall: 0.4528

In [31]:
results = model.evaluate(X_train_scaled, y_train, return_dict=True)

print(results)

707/707 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7361 - loss: 0.5747 - precision: 0.6347 - recall: 0.5387
{'accuracy': 0.7360994219779968, 'loss': 0.5746505856513977, 'precision': 0.6346739530563354, 'recall': 0.53866046667099}

In [32]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.5
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy (cv set): 0.7166432584269663
              precision    recall  f1-score   support

         0.0       0.76      0.84      0.79      3710
         1.0       0.62      0.49      0.55      1986

    accuracy                           0.72      5696
   macro avg       0.69      0.67      0.67      5696
weighted avg       0.71      0.72      0.71      5696

[[3099  611]
 [1003  983]]

In [33]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.45
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

178/178 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy (cv set): 0.7192766853932584
              precision    recall  f1-score   support

         0.0       0.79      0.78      0.78      3710
         1.0       0.60      0.60      0.60      1986

    accuracy                           0.72      5696
   macro avg       0.69      0.69      0.69      5696
weighted avg       0.72      0.72      0.72      5696

[[2906  804]
 [ 795 1191]]

In [34]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.40
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

178/178 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Accuracy (cv set): 0.6889044943820225
              precision    recall  f1-score   support

         0.0       0.83      0.66      0.73      3710
         1.0       0.54      0.74      0.62      1986

    accuracy                           0.69      5696
   macro avg       0.68      0.70      0.68      5696
weighted avg       0.73      0.69      0.70      5696

[[2450 1260]
 [ 512 1474]]

In [35]:
#5th fold of 5-fold cross-validation will use homology partition 4 as the validation set
train_df = df[df["Partition"].isin([0, 1, 2, 3])]
X_train = np.stack(train_df["input_vectors"].values)
y_train = np.stack(train_df["Nucleus"].values)

cv_df = df[df["Partition"] == 4]
X_cv = np.stack(cv_df["input_vectors"].values)
y_cv = np.stack(cv_df["Nucleus"].values)

X_train_scaled = scaler.fit_transform(X_train)
X_cv_scaled = scaler.transform(X_cv)

model.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7278 - loss: 0.5786 - precision: 0.6342 - recall: 0.4558
Epoch 2/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7255 - loss: 0.5803 - precision: 0.6294 - recall: 0.4527
Epoch 3/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7283 - loss: 0.5784 - precision: 0.6365 - recall: 0.4532
Epoch 4/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7281 - loss: 0.5791 - precision: 0.6363 - recall: 0.4524
Epoch 5/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7283 - loss: 0.5793 - precision: 0.6367 - recall: 0.4529
Epoch 6/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7283 - loss: 0.5781 - precision: 0.6354 - recall: 0.4558
Epoch 7/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7297 - loss: 0.5792 - precision: 0.6425 - recall: 0.4472
Epoch 8/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7300 - loss: 0.5789 - precision: 0.6417 - recall: 0.4514
Epoch 9/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7310 - loss: 0.5794 - precision: 0.6450 - recall: 0.4500
Epoch 10/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7265 - loss: 0.5803 - precision: 0.6328 - recall: 0.4501
Epoch 11/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7285 - loss: 0.5789 - precision: 0.6367 - recall: 0.4541
Epoch 12/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7284 - loss: 0.5781 - precision: 0.6360 - recall: 0.4550
Epoch 13/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7287 - loss: 0.5788 - precision: 0.6363 - recall: 0.4563
Epoch 14/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7256 - loss: 0.5793 - precision: 0.6315 - recall: 0.4472
Epoch 15/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7251 - loss: 0.5806 - precision: 0.6310 - recall: 0.4457
Epoch 16/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7290 - loss: 0.5782 - precision: 0.6369 - recall: 0.4566
Epoch 17/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7281 - loss: 0.5789 - precision: 0.6358 - recall: 0.4538
Epoch 18/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7259 - loss: 0.5786 - precision: 0.6310 - recall: 0.4511
Epoch 19/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7265 - loss: 0.5796 - precision: 0.6353 - recall: 0.4437
Epoch 20/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7281 - loss: 0.5789 - precision: 0.6362 - recall: 0.4527
Epoch 21/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7248 - loss: 0.5794 - precision: 0.6276 - recall: 0.4523
Epoch 22/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7280 - loss: 0.5792 - precision: 0.6374 - recall: 0.4488
Epoch 23/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7276 - loss: 0.5796 - precision: 0.6352 - recall: 0.4516
Epoch 24/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7267 - loss: 0.5791 - precision: 0.6361 - recall: 0.4432
Epoch 25/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7305 - loss: 0.5786 - precision: 0.6400 - recall: 0.4590
Epoch 26/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7262 - loss: 0.5784 - precision: 0.6312 - recall: 0.4526
Epoch 27/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7293 - loss: 0.5776 - precision: 0.6357 - recall: 0.4623
Epoch 28/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7288 - loss: 0.5782 - precision: 0.6381 - recall: 0.4526
Epoch 29/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7271 - loss: 0.5784 - precision: 0.6337 - recall: 0.4520
Epoch 30/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7254 - loss: 0.5786 - precision: 0.6327 - recall: 0.4429
Epoch 31/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7286 - loss: 0.5801 - precision: 0.6378 - recall: 0.4516
Epoch 32/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7262 - loss: 0.5786 - precision: 0.6338 - recall: 0.4458
Epoch 33/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7314 - loss: 0.5786 - precision: 0.6423 - recall: 0.4592
Epoch 34/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7299 - loss: 0.5790 - precision: 0.6414 - recall: 0.4513
Epoch 35/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7279 - loss: 0.5793 - precision: 0.6349 - recall: 0.4549
Epoch 36/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7294 - loss: 0.5776 - precision: 0.6384 - recall: 0.4561
Epoch 37/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7262 - loss: 0.5788 - precision: 0.6309 - recall: 0.4529
Epoch 38/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7271 - loss: 0.5795 - precision: 0.6370 - recall: 0.4436
Epoch 39/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7268 - loss: 0.5777 - precision: 0.6327 - recall: 0.4527
Epoch 40/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7269 - loss: 0.5804 - precision: 0.6328 - recall: 0.4528
Epoch 41/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7260 - loss: 0.5794 - precision: 0.6317 - recall: 0.4500
Epoch 42/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7286 - loss: 0.5795 - precision: 0.6399 - recall: 0.4462
Epoch 43/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7283 - loss: 0.5792 - precision: 0.6389 - recall: 0.4466
Epoch 44/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7289 - loss: 0.5794 - precision: 0.6377 - recall: 0.4538
Epoch 45/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7293 - loss: 0.5789 - precision: 0.6385 - recall: 0.4545
Epoch 46/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7279 - loss: 0.5796 - precision: 0.6359 - recall: 0.4515
Epoch 47/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7300 - loss: 0.5783 - precision: 0.6397 - recall: 0.4562
Epoch 48/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7269 - loss: 0.5790 - precision: 0.6340 - recall: 0.4496
Epoch 49/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7272 - loss: 0.5797 - precision: 0.6341 - recall: 0.4519
Epoch 50/50
714/714 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7290 - loss: 0.5783 - precision: 0.6401 - recall: 0.4485

In [36]:
results = model.evaluate(X_train_scaled, y_train, return_dict=True)

print(results)

714/714 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7374 - loss: 0.5673 - precision: 0.6699 - recall: 0.4366
{'accuracy': 0.7374458312988281, 'loss': 0.5672984719276428, 'precision': 0.6699203252792358, 'recall': 0.43658316135406494}

In [37]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.5
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

171/171 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy (cv set): 0.7087147564994507
              precision    recall  f1-score   support

         0.0       0.72      0.89      0.79      3445
         1.0       0.67      0.41      0.51      2017

    accuracy                           0.71      5462
   macro avg       0.70      0.65      0.65      5462
weighted avg       0.70      0.71      0.69      5462

[[3049  396]
 [1195  822]]

In [38]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.45
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

171/171 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy (cv set): 0.712925668253387
              precision    recall  f1-score   support

         0.0       0.74      0.83      0.78      3445
         1.0       0.64      0.51      0.57      2017

    accuracy                           0.71      5462
   macro avg       0.69      0.67      0.68      5462
weighted avg       0.71      0.71      0.71      5462

[[2860  585]
 [ 983 1034]]

In [39]:
y_prob = model.predict(X_cv_scaled)
threshold = 0.40
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (cv set):", accuracy_score(y_cv, yhat))
print(classification_report(y_cv, yhat))
print(confusion_matrix(y_cv, yhat))

171/171 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
Accuracy (cv set): 0.7070670084218235
              precision    recall  f1-score   support

         0.0       0.77      0.76      0.77      3445
         1.0       0.60      0.62      0.61      2017

    accuracy                           0.71      5462
   macro avg       0.69      0.69      0.69      5462
weighted avg       0.71      0.71      0.71      5462

[[2621  824]
 [ 776 1241]]

In [40]:
#final model
X_train = np.stack(df["input_vectors"].values)
y_train = np.stack(df["Nucleus"].values)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model.fit(X_train_scaled, y_train, epochs = 50)

Epoch 1/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7254 - loss: 0.5815 - precision: 0.6347 - recall: 0.4718
Epoch 2/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7283 - loss: 0.5820 - precision: 0.6422 - recall: 0.4717
Epoch 3/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.7266 - loss: 0.5822 - precision: 0.6398 - recall: 0.4665
Epoch 4/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.7247 - loss: 0.5820 - precision: 0.6345 - recall: 0.4680
Epoch 5/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7232 - loss: 0.5823 - precision: 0.6318 - recall: 0.4650
Epoch 6/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7255 - loss: 0.5823 - precision: 0.6351 - recall: 0.4721
Epoch 7/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7231 - loss: 0.5825 - precision: 0.6309 - recall: 0.4667
Epoch 8/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7265 - loss: 0.5819 - precision: 0.6365 - recall: 0.4748
Epoch 9/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7228 - loss: 0.5817 - precision: 0.6306 - recall: 0.4656
Epoch 10/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7242 - loss: 0.5819 - precision: 0.6351 - recall: 0.4631
Epoch 11/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7246 - loss: 0.5810 - precision: 0.6376 - recall: 0.4587
Epoch 12/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7255 - loss: 0.5818 - precision: 0.6390 - recall: 0.4612
Epoch 13/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7259 - loss: 0.5819 - precision: 0.6379 - recall: 0.4666
Epoch 14/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7236 - loss: 0.5828 - precision: 0.6323 - recall: 0.4662
Epoch 15/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7255 - loss: 0.5822 - precision: 0.6382 - recall: 0.4633
Epoch 16/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7237 - loss: 0.5830 - precision: 0.6341 - recall: 0.4624
Epoch 17/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7243 - loss: 0.5823 - precision: 0.6363 - recall: 0.4602
Epoch 18/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7258 - loss: 0.5833 - precision: 0.6400 - recall: 0.4606
Epoch 19/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7236 - loss: 0.5813 - precision: 0.6334 - recall: 0.4632
Epoch 20/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7255 - loss: 0.5813 - precision: 0.6364 - recall: 0.4682
Epoch 21/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7229 - loss: 0.5827 - precision: 0.6318 - recall: 0.4630
Epoch 22/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7251 - loss: 0.5815 - precision: 0.6350 - recall: 0.4690
Epoch 23/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7258 - loss: 0.5820 - precision: 0.6377 - recall: 0.4666
Epoch 24/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7265 - loss: 0.5811 - precision: 0.6409 - recall: 0.4632
Epoch 25/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7235 - loss: 0.5827 - precision: 0.6334 - recall: 0.4628
Epoch 26/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7251 - loss: 0.5819 - precision: 0.6364 - recall: 0.4656
Epoch 27/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7234 - loss: 0.5821 - precision: 0.6324 - recall: 0.4643
Epoch 28/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.7247 - loss: 0.5825 - precision: 0.6348 - recall: 0.4668
Epoch 29/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7284 - loss: 0.5816 - precision: 0.6407 - recall: 0.4761
Epoch 30/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7258 - loss: 0.5820 - precision: 0.6371 - recall: 0.4686
Epoch 31/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7232 - loss: 0.5825 - precision: 0.6340 - recall: 0.4590
Epoch 32/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7247 - loss: 0.5825 - precision: 0.6367 - recall: 0.4620
Epoch 33/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7231 - loss: 0.5816 - precision: 0.6307 - recall: 0.4672
Epoch 34/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7259 - loss: 0.5814 - precision: 0.6386 - recall: 0.4649
Epoch 35/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7239 - loss: 0.5827 - precision: 0.6326 - recall: 0.4675
Epoch 36/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7264 - loss: 0.5820 - precision: 0.6381 - recall: 0.4693
Epoch 37/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7235 - loss: 0.5820 - precision: 0.6344 - recall: 0.4601
Epoch 38/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7247 - loss: 0.5819 - precision: 0.6343 - recall: 0.4684
Epoch 39/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.7256 - loss: 0.5815 - precision: 0.6372 - recall: 0.4671
Epoch 40/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7272 - loss: 0.5824 - precision: 0.6395 - recall: 0.4715
Epoch 41/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7228 - loss: 0.5826 - precision: 0.6308 - recall: 0.4647
Epoch 42/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7249 - loss: 0.5813 - precision: 0.6345 - recall: 0.4694
Epoch 43/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7253 - loss: 0.5818 - precision: 0.6379 - recall: 0.4632
Epoch 44/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7243 - loss: 0.5821 - precision: 0.6345 - recall: 0.4650
Epoch 45/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7235 - loss: 0.5826 - precision: 0.6329 - recall: 0.4642
Epoch 46/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7224 - loss: 0.5819 - precision: 0.6326 - recall: 0.4572
Epoch 47/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7250 - loss: 0.5823 - precision: 0.6367 - recall: 0.4638
Epoch 48/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7219 - loss: 0.5810 - precision: 0.6289 - recall: 0.4640
Epoch 49/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.7219 - loss: 0.5821 - precision: 0.6307 - recall: 0.4590
Epoch 50/50
885/885 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.7226 - loss: 0.5829 - precision: 0.6297 - recall: 0.4669

In [41]:
results = model.evaluate(X_train_scaled, y_train, return_dict=True)

print(results)

885/885 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.7340 - loss: 0.5751 - precision: 0.6611 - recall: 0.4622
{'accuracy': 0.7339504361152649, 'loss': 0.5750557780265808, 'precision': 0.6611241698265076, 'recall': 0.46224281191825867}

In [44]:
y_prob = model.predict(X_test_scaled)
threshold = 0.40
yhat = (y_prob >= threshold).astype(int).ravel()

print("Accuracy (test set):", accuracy_score(y_test, yhat))
print(classification_report(y_test, yhat))
print(confusion_matrix(y_test, yhat))

54/54 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Accuracy (test set): 0.6051252184041933
              precision    recall  f1-score   support

           0       0.59      0.58      0.58       824
           1       0.62      0.63      0.62       893

    accuracy                           0.61      1717
   macro avg       0.60      0.60      0.60      1717
weighted avg       0.60      0.61      0.60      1717

[[477 347]
 [331 562]]